### ISSUE TITLE
Any good news for this framework?

### ISSUE THREAD

**Issue by one-next** [nhnent/haste.framework#10]
Hi, Ethan,
    I found the framework very good. It own clearly code structure. I guess it will be powerful. Do you continue, or give it up?  I'm studying, try to know how to use it. But there is no more API document, no more comments. Actually that's feel not good.

**Comment by hide1202** [comment]
@one-next Thank you for your interest. We use this framework for our service in Korea. So we continue to improve and support for this framework and our service. But this framework has lack documentations, so will fill API, example, etc. documentations.

**Comment by one-next** [comment]
@hide1202  thanks your reply & your team's selflessness. Waiting for more API , examples and so on .  I will continue follow your steps. Can you share toast-haste run-time environment? BTW,  the framework contain the Database solution(No-SQL or others)?

**Comment by hide1202** [comment]
@one-next We run a service using TOAST Haste on CentOS 6.X, JVM(OpenJDK 8). If you want to run a application using TOAST Haste, you run on JVM, any operating systems.
And we develop the framework for real-time multi-play game, so this framework doesn't contain DB solutions.
A our service contains Redis for user sessions. If you want to use databases, just use them. TOAST Haste supports various callbacks, for example callbacks when connecting a user, disconnecting a user, receiving a message, etc.
But you consider the elapsed time of a task, because the framework contains RTT calculation. So you MUST not long tasks.

**Comment by one-next** [comment]
Cool, thanks very much. Our  linux is CentOS 6.9, JDK 7(Switch to 8).  I will try it in my free time. @hide1202
